
CREATE TABLE TEST_TV (
	VIDEO_NAME VARCHAR(30),
	VIEW_CNT INT,
	NAME_CAST VARCHAR(30),
	CAST_NUM INT
	);

INSERT INTO TEST_TV VALUES ('아저씨','365', '원빈', '5');
INSERT INTO TEST_TV VALUES ('바비', '333', '마고로비', '10');
INSERT INTO TEST_TV VALUES ('바비2', '444', '마고로비', '22');
INSERT INTO TEST_TV VALUES ('아저씨2','3633', '원빈', '33');

SELECT * FROM TEST_TV;

DELETE FROM TEST_TV WHERE VIDEO_NAME = '아저씨';

CREATE TABLE CAST_INFO (
	VIDEO_NAME VARCHAR(40),
	MAIN_ACT VARCHAR(30),
	SUB_ACT VARCHAR(30),
	MAIN_AGE INT,
	SUB_AGE INT
	);

INSERT INTO CAST_INFO VALUES ('아저씨', '원빈', '꼬맹', '30', '14');
INSERT INTO CAST_INFO VALUES ('아저씨2', '원빈', '꼬맹2', '40', '24');
INSERT INTO CAST_INFO VALUES ('바비', '마고로비', '디카프리오', '35', '50');

SELECT * FROM CAST_INFO;

SHOW TABLES;

SELECT A.VIDEO_NAME, A.VIEW_CNT, B.MAIN_ACT, B.SUB_ACT, B.MAIN_AGE, B.SUB_AGE  
	FROM TEST_TV A, CAST_INFO B
	WHERE A.VIDEO_NAME = B.VIDEO_NAME;


	
	
	
	
	
	
